dist: xenial

language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'

install:
    - composer install
    - cd e2e
    - php testPharAutoloader.php

    # this should exit with 1
    - ../rector.phar process data --set dead-code --dry-run

    # run phar
    - php rector
    - php rector.phar

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache
