<?php

declare (strict_types=1);
namespace _PhpScoper2a4e7ab1ecbc\Rector\BetterPhpDocParser\AnnotationReader;

use _PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\AnnotationReader;
use _PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\AnnotationRegistry;
use _PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\DocParser;
use _PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\Reader;
use _PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingAnnotationReader;
use _PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingDocParser;
final class AnnotationReaderFactory
{
    /**
     * @var string[]
     */
    private const IGNORED_NAMES = [
        '_PhpScoper2a4e7ab1ecbc\\ORM\\GeneratedValue',
        'GeneratedValue',
        '_PhpScoper2a4e7ab1ecbc\\ORM\\InheritanceType',
        'InheritanceType',
        '_PhpScoper2a4e7ab1ecbc\\ORM\\OrderBy',
        'OrderBy',
        '_PhpScoper2a4e7ab1ecbc\\ORM\\DiscriminatorMap',
        'DiscriminatorMap',
        '_PhpScoper2a4e7ab1ecbc\\ORM\\UniqueEntity',
        'UniqueEntity',
        '_PhpScoper2a4e7ab1ecbc\\Gedmo\\SoftDeleteable',
        'SoftDeleteable',
        '_PhpScoper2a4e7ab1ecbc\\Gedmo\\Slug',
        'Slug',
        '_PhpScoper2a4e7ab1ecbc\\Gedmo\\SoftDeleteable',
        'SoftDeleteable',
        '_PhpScoper2a4e7ab1ecbc\\Gedmo\\Blameable',
        'Blameable',
        '_PhpScoper2a4e7ab1ecbc\\Gedmo\\Versioned',
        'Versioned',
        // nette @inject dummy annotation
        'inject',
    ];
    public function create() : \_PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\Reader
    {
        \_PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader('class_exists');
        // generated
        $annotationReader = $this->createAnnotationReader();
        // without this the reader will try to resolve them and fails with an exception
        // don't forget to add it to "stubs/Doctrine/Empty" directory, because the class needs to exists
        // and run "composer dump-autoload", because the directory is loaded by classmap
        foreach (self::IGNORED_NAMES as $ignoredName) {
            $annotationReader::addGlobalIgnoredName($ignoredName);
        }
        // warning: nested tags must be parse-able, e.g. @ORM\Table must include @ORM\UniqueConstraint!
        return $annotationReader;
    }
    /**
     * @return AnnotationReader|ConstantPreservingAnnotationReader
     */
    private function createAnnotationReader() : \_PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\Reader
    {
        // these 2 classes are generated by "bin/rector sync-annotation-parser" command
        if (\class_exists(\_PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingAnnotationReader::class) && \class_exists(\_PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingDocParser::class)) {
            $constantPreservingDocParser = new \_PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingDocParser();
            return new \_PhpScoper2a4e7ab1ecbc\Rector\DoctrineAnnotationGenerated\ConstantPreservingAnnotationReader($constantPreservingDocParser);
        }
        // fallback for testing incompatibilities
        return new \_PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\AnnotationReader(new \_PhpScoper2a4e7ab1ecbc\Doctrine\Common\Annotations\DocParser());
    }
}
