<?php

declare (strict_types=1);
namespace _PhpScoper2a4e7ab1ecbc;

use _PhpScoper2a4e7ab1ecbc\Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveAssignOfVoidReturnFunctionRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\BinaryOp\RemoveDuplicatedInstanceOfRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\BooleanAnd\RemoveAndTrueRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassConst\RemoveUnusedClassConstantRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassConst\RemoveUnusedPrivateConstantRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDeadRecursiveClassMethodRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Concat\RemoveConcatAutocastRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Function_\RemoveUnusedFunctionRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\If_\RemoveUnusedNonEmptyArrayBeforeForeachRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\MethodCall\RemoveEmptyMethodCallRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Switch_\RemoveDuplicatedCaseInSwitchRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Ternary\TernaryToBooleanOrFalseToBooleanAndRector;
use _PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\TryCatch\RemoveDeadTryCatchRector;
use _PhpScoper2a4e7ab1ecbc\Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
return static function (\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator $containerConfigurator) : void {
    $services = $containerConfigurator->services();
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Expression\RemoveDeadStmtRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Array_\RemoveDuplicatedArrayKeyRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Foreach_\RemoveUnusedForeachKeyRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\StaticCall\RemoveParentCallWithoutParentRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveEmptyClassMethodRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Property\RemoveUnusedPrivatePropertyRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveDoubleAssignRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveUnusedParameterRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Expression\SimplifyMirrorAssignRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveOverriddenValuesRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassConst\RemoveUnusedPrivateConstantRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPrivateMethodRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveCodeAfterReturnRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDeadConstructorRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveDeadReturnRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\For_\RemoveDeadIfForeachForRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\BooleanAnd\RemoveAndTrueRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\MethodCall\RemoveDefaultArgumentValueRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Concat\RemoveConcatAutocastRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\CodeQuality\Rector\Return_\SimplifyUselessVariableRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDelegatingParentCallRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\BinaryOp\RemoveDuplicatedInstanceOfRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Switch_\RemoveDuplicatedCaseInSwitchRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Class_\RemoveUnusedDoctrineEntityMethodAndPropertyRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Property\RemoveSetterOnlyPropertyAndMethodCallRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\PropertyProperty\RemoveNullPropertyInitializationRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Stmt\RemoveUnreachableStatementRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\If_\SimplifyIfElseWithSameContentRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Ternary\TernaryToBooleanOrFalseToBooleanAndRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\PHPUnit\Rector\ClassMethod\RemoveEmptyTestMethodRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\TryCatch\RemoveDeadTryCatchRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassConst\RemoveUnusedClassConstantRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveUnusedVariableAssignRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\FunctionLike\RemoveDuplicatedIfReturnRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Function_\RemoveUnusedFunctionRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\If_\RemoveUnusedNonEmptyArrayBeforeForeachRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\Assign\RemoveAssignOfVoidReturnFunctionRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\ClassMethod\RemoveDeadRecursiveClassMethodRector::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\DeadCode\Rector\MethodCall\RemoveEmptyMethodCallRector::class);
};
