<?php

declare (strict_types=1);
namespace RectorPrefix2020DecSat;

use Rector\Generic\Rector\String_\StringToClassConstantRector;
use Rector\Generic\ValueObject\StringToClassConstant;
use Rector\Renaming\Rector\Name\RenameClassRector;
use RectorPrefix2020DecSat\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\SymfonyPhpConfig\ValueObjectInliner;
# see: https://laravel.com/docs/5.2/upgrade
return static function (\RectorPrefix2020DecSat\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator $containerConfigurator) : void {
    $services = $containerConfigurator->services();
    $services->set(\Rector\Renaming\Rector\Name\RenameClassRector::class)->call('configure', [[\Rector\Renaming\Rector\Name\RenameClassRector::OLD_TO_NEW_CLASSES => ['RectorPrefix2020DecSat\\Illuminate\\Auth\\Access\\UnauthorizedException' => 'RectorPrefix2020DecSat\\Illuminate\\Auth\\Access\\AuthorizationException', 'RectorPrefix2020DecSat\\Illuminate\\Http\\Exception\\HttpResponseException' => 'RectorPrefix2020DecSat\\Illuminate\\Foundation\\Validation\\ValidationException', 'RectorPrefix2020DecSat\\Illuminate\\Foundation\\Composer' => 'RectorPrefix2020DecSat\\Illuminate\\Support\\Composer']]]);
    $services->set(\Rector\Generic\Rector\String_\StringToClassConstantRector::class)->call('configure', [[\Rector\Generic\Rector\String_\StringToClassConstantRector::STRINGS_TO_CLASS_CONSTANTS => \Symplify\SymfonyPhpConfig\ValueObjectInliner::inline([new \Rector\Generic\ValueObject\StringToClassConstant('artisan.start', 'RectorPrefix2020DecSat\\Illuminate\\Console\\Events\\ArtisanStarting', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('auth.attempting', 'RectorPrefix2020DecSat\\Illuminate\\Auth\\Events\\Attempting', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('auth.login', 'RectorPrefix2020DecSat\\Illuminate\\Auth\\Events\\Login', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('auth.logout', 'RectorPrefix2020DecSat\\Illuminate\\Auth\\Events\\Logout', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('cache.missed', 'RectorPrefix2020DecSat\\Illuminate\\Cache\\Events\\CacheMissed', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('cache.hit', 'RectorPrefix2020DecSat\\Illuminate\\Cache\\Events\\CacheHit', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('cache.write', 'RectorPrefix2020DecSat\\Illuminate\\Cache\\Events\\KeyWritten', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('cache.delete', 'RectorPrefix2020DecSat\\Illuminate\\Cache\\Events\\KeyForgotten', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('illuminate.query', 'RectorPrefix2020DecSat\\Illuminate\\Database\\Events\\QueryExecuted', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('illuminate.queue.before', 'RectorPrefix2020DecSat\\Illuminate\\Queue\\Events\\JobProcessing', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('illuminate.queue.after', 'RectorPrefix2020DecSat\\Illuminate\\Queue\\Events\\JobProcessed', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('illuminate.queue.failed', 'RectorPrefix2020DecSat\\Illuminate\\Queue\\Events\\JobFailed', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('illuminate.queue.stopping', 'RectorPrefix2020DecSat\\Illuminate\\Queue\\Events\\WorkerStopping', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('mailer.sending', 'RectorPrefix2020DecSat\\Illuminate\\Mail\\Events\\MessageSending', 'class'), new \Rector\Generic\ValueObject\StringToClassConstant('router.matched', 'RectorPrefix2020DecSat\\Illuminate\\Routing\\Events\\RouteMatched', 'class')])]]);
};
