<?php

declare (strict_types=1);
namespace _PhpScoper2a4e7ab1ecbc;

use _PhpScoper2a4e7ab1ecbc\Doctrine\Inflector\Inflector;
use _PhpScoper2a4e7ab1ecbc\Doctrine\Inflector\Rules\English\InflectorFactory;
use _PhpScoper2a4e7ab1ecbc\PhpParser\BuilderFactory;
use _PhpScoper2a4e7ab1ecbc\PhpParser\Lexer;
use _PhpScoper2a4e7ab1ecbc\PhpParser\NodeFinder;
use _PhpScoper2a4e7ab1ecbc\PhpParser\NodeVisitor\CloningVisitor;
use _PhpScoper2a4e7ab1ecbc\PhpParser\Parser;
use _PhpScoper2a4e7ab1ecbc\PhpParser\ParserFactory;
use _PhpScoper2a4e7ab1ecbc\Rector\Core\Bootstrap\NoRectorsLoadedReporter;
use _PhpScoper2a4e7ab1ecbc\Rector\Core\Configuration\RectorClassesProvider;
use _PhpScoper2a4e7ab1ecbc\Rector\Core\Console\ConsoleApplication;
use _PhpScoper2a4e7ab1ecbc\Rector\Core\PhpParser\Parser\NikicPhpParserFactory;
use _PhpScoper2a4e7ab1ecbc\Rector\Core\PhpParser\Parser\PhpParserLexerFactory;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Application as SymfonyApplication;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Descriptor\TextDescriptor;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Style\SymfonyStyle;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use function _PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref;
use _PhpScoper2a4e7ab1ecbc\Symfony\Component\Filesystem\Filesystem;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Console\Command\CommandNaming;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Parameter\ParameterProvider;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Reflection\PrivatesAccessor;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Reflection\PrivatesCaller;
use _PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Strings\StringFormatConverter;
use _PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\FileSystemFilter;
use _PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\Finder\FinderSanitizer;
use _PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\SmartFileSystem;
return static function (\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator $containerConfigurator) : void {
    $services = $containerConfigurator->services();
    $services->defaults()->public()->autowire()->autoconfigure();
    $services->load('Rector\\Core\\', __DIR__ . '/../src')->exclude([__DIR__ . '/../src/Rector', __DIR__ . '/../src/Exception', __DIR__ . '/../src/DependencyInjection/CompilerPass', __DIR__ . '/../src/DependencyInjection/Loader', __DIR__ . '/../src/PhpParser/Builder', __DIR__ . '/../src/HttpKernel', __DIR__ . '/../src/ValueObject', __DIR__ . '/../src/Bootstrap', __DIR__ . '/../src/PhpParser/Node/CustomNode']);
    $services->alias(\_PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Application::class, \_PhpScoper2a4e7ab1ecbc\Rector\Core\Console\ConsoleApplication::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\Core\Bootstrap\NoRectorsLoadedReporter::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Descriptor\TextDescriptor::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\ParserFactory::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\BuilderFactory::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\NodeVisitor\CloningVisitor::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\NodeFinder::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\Parser::class)->factory([\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref(\_PhpScoper2a4e7ab1ecbc\Rector\Core\PhpParser\Parser\NikicPhpParserFactory::class), 'create']);
    $services->set(\_PhpScoper2a4e7ab1ecbc\PhpParser\Lexer::class)->factory([\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref(\_PhpScoper2a4e7ab1ecbc\Rector\Core\PhpParser\Parser\PhpParserLexerFactory::class), 'create']);
    // symplify/package-builder
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symfony\Component\Filesystem\Filesystem::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Reflection\PrivatesAccessor::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Reflection\PrivatesCaller::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\Finder\FinderSanitizer::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\FileSystemFilter::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Parameter\ParameterProvider::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Parameter\ParameterProvider::class)->arg('$container', \_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref('service_container'));
    $services->set(\_PhpScoper2a4e7ab1ecbc\Rector\Core\Configuration\RectorClassesProvider::class)->arg('$container', \_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref('service_container'));
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Console\Command\CommandNaming::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\SmartFileSystem\SmartFileSystem::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Strings\StringFormatConverter::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Symfony\Component\Console\Style\SymfonyStyle::class)->factory([\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref(\_PhpScoper2a4e7ab1ecbc\Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory::class), 'create']);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Doctrine\Inflector\Rules\English\InflectorFactory::class);
    $services->set(\_PhpScoper2a4e7ab1ecbc\Doctrine\Inflector\Inflector::class)->factory([\_PhpScoper2a4e7ab1ecbc\Symfony\Component\DependencyInjection\Loader\Configurator\ref(\_PhpScoper2a4e7ab1ecbc\Doctrine\Inflector\Rules\English\InflectorFactory::class), 'build']);
};
