name: PHP Parser 3

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    php_parser_3:
        runs-on: ubuntu-latest

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            # wait for deploy to packagist
            -   run: sleep 70

            -   run: composer require nikic/php-parser:^3.1 --ansi
            -   run: composer require rector/rector-prefixed:dev-main --dev --ansi
            -   run: vendor/bin/rector list --ansi
