name: PHP Parser 3

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    php_parser_3:
        runs-on: ubuntu-latest

        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.1
                    coverage: none

            -   run: composer require nikic/php-parser:^3.1
            -   run: composer require rector/rector-prefixed:^0.10
            -   run: vendor/bin/rector list
