# inspired by https://github.com/Symplify/EasyCodingStandardPrefixed/blob/master/.github/workflows/code_checks.yaml
name: Run PHAR

on: [pull_request, push]

jobs:
    run_phar:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: "Run PHARs"
                run: |
                    php rector --debug --ansi
                    php rector.phar --debug --ansi
                    ./rector --debug --ansi
                    ./rector.phar --debug --ansi
