name: Simple Test

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    simple_test:
        runs-on: ubuntu-latest
        steps:
            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer require rector/rector-prefixed
            -   run: composer require phpunit/phpunit --dev
            -   run: vendor/bin/phpunit tests/Rector/RenameSimpleRectorTest.php
